name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Prepare tag for release notes
      id: prep
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/} | sed 's/\.//g')"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          See [${{ github.ref_name }} CHANGELOG entry](https://github.com/kwhitley/itty-router/blob/v5.x/CHANGELOG.md#${{ steps.prep.outputs.tag }}) for notes
        draft: false
        prerelease: false
